version: 2
updates:
- package-ecosystem: gomod
  directory: "/backend"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gorm.io/gorm
    versions:
    - 1.20.12
    - 1.21.1
    - 1.21.2
    - 1.21.3
    - 1.21.4
    - 1.21.5
    - 1.21.6
    - 1.21.7
    - 1.21.8
  - dependency-name: github.com/jinzhu/copier
    versions:
    - 0.2.5
    - 0.2.9
  - dependency-name: github.com/gin-gonic/gin
    versions:
    - 1.7.0
  - dependency-name: github.com/go-playground/validator/v10
    versions:
    - 10.4.2
  - dependency-name: github.com/sirupsen/logrus
    versions:
    - 1.7.1
    - 1.8.0
