version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./backend:/go/src
    environment: 
      MYSQL_USER: random
      MYSQL_PASSWORD: random
      DBHOST: db
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URL: http://127.0.0.1:3000/google/callback
  db:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/mysql
      - ./logs:/var/log/mysql
    ports:
      - 33006:3306
    environment:
      MYSQL_DATABASE: go-random
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: random
      MYSQL_PASSWORD: random
      BIND-ADDRESS: 0.0.0.0
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 16379:6379
    volumes:
      - redis-data:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile-fe
    volumes:
     - ./frontend:/usr/src/app
    environment:
      REACT_APP_API_BASE_URL: http://127.0.0.1:8080
      REACT_APP_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      REACT_APP_GOOGLE_REDIRECT_URI: http://127.0.0.1:3000/google/callback
    command: sh -c "yarn install && yarn start"
    ports:
      - "3000:3000"
    tty: true
volumes: 
  db-data:
  redis-data:
