version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./:/go/src
      - /go/src/db-data
      - /go/src/logs
      - /go/src/web
    environment: 
      MYSQL_USER: random
      MYSQL_PASSWORD: random
      DBHOST: db
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
  db:
    image: mysql:8.0
    volumes:
      - ./db-data:/var/lib/mysql
      - ./logs:/var/log/mysql
    ports:
      - 33006:3306
    environment:
      MYSQL_DATABASE: go-random
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: random
      MYSQL_PASSWORD: random
      BIND-ADDRESS: 0.0.0.0
  web:
    build:
      context: .
      dockerfile: Dockerfile-fe
    volumes:
     - ./web:/usr/src/app
    command: sh -c "yarn start"
    ports:
      - "3000:3000"
    tty: true
volumes: 
  db-data:
